services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file: ./.env
    environment:
      POSTGRES_USER: $PGUSER
      POSTGRES_PASSWORD: $PGPASSWORD
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
  adminer:
    image: adminer
    restart: always
    env_file: ./.env
    environment:
      ADMINER_DESIGN: dracula
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DEFAULT_USER: $PGUSER
    ports:
      - 8080:8080